log:
  path: 'logs/'
  clear_old_logs: true
  log_format: '[%(levelname)s] [%(created)f] [%(filename)s] %(message)s'
carla:
  host: 127.0.0.1
  fidelity: 'Low'
  port: 2000
  timeout: 20
  sync: true
  fixed_delta_seconds: 0.05 # update rate 1 / FPS
traffic_manager:
  active: true
  sync: true # must be the same as carla sync
  seed: 0
  port: 8001
scenario_runner:
  debug: false
  dev_mode: false
  follow_ego: true
  json: ./example_scenario.json
  route_id: 0
  agent: srunner/autoagents/autoware_agent
  initialisation_budget: 200 # ticks
  algorithm:
    iterations: 10
    path: algorithms/hill_climb
    args: # will be passed into the algorithm class as a dict
      lanelet_path: /autoware_scenario_runner/algorithms/resources/Town01.osm
      radius: 10
