log:
  path: 'logs/'
  clear_old_logs: true
carla:
  host: 127.0.0.1
  port: 2000
  timeout: 20
  sync: true
  fixed_delta_seconds: 0.05 # update rate 1 / FPS
  debug: false
traffic_manager:
  active: false
  sync: true # must be the same as carla sync
  port: 8000
scenario_runner:
  json: ./example_scenario.json
  debug: false
  route_id: 0
  in_docker: true # used for dev
algorithm:
  iterations: 1000
  hyperparmaters: # will be passed into the algorithm class
