log:
  path: 'logs/'
  clear_old_logs: true
  log_format: '[%(levelname)s] [%(asctime)s] [%(message)s] [%(filename)s]:[%(lineno)d]'
carla:
  host: 127.0.0.1
  fidelity: 'Low'
  port: 2000
  timeout: 20
  sync: true
  fixed_delta_seconds: 0.05 # update rate 1 / FPS
traffic_manager:
  active: false
  sync: true # must be the same as carla sync
  seed: 0
  port: 8001
scenario_runner:
  debug: false
  dev_mode: false
  json: ./example_scenario.json
  route_id: 0
  agent: srunner/autoagents/autoware_agent
  initialisation_budget: 300 # ticks
  algorithm:
    iterations: 10
    path: algorithms/test_alg # relative path
    args: # will be passed into the algorithm class as a dict
      test_arg: 10
