import xml.etree.ElementTree as ET
from xml.etree.ElementTree import Element

from srunner.scenariomanager.carla_data_provider import CarlaDataProvider

import carla
import logging


class EnvironmentConfig(object):
    """
    Simple object to store information about the initial environment setup for the scenario loop
    """

    def __init__(self) -> None:
        self.town: str = ""
        self.ego_model: str = ""
        self.ego_name: str = ""
        self.ego_spawn: carla.Transform | None = None
        self.sensor_config: list[DefaultSensor] = []
        self.route_id: int = 0


class DefaultSensor(object):
    """
    A class to encapsulate information about a basic sensor
    """

    def __init__(self) -> None:
        self.type: str = ""
        self.id: str = ""
        self.spawn: carla.Transform | None = None

    def _spawn(self, bp_library, vehicle) -> None:
        sensor_bp = bp_library.find(str(self.type))

        ignored_params = [
            "__class__",
            "__delattr__",
            "__dict__",
            "__dir__",
            "__doc__",
            "__eq__",
            "__format__",
            "__ge__",
            "__getattribute__",
            "__gt__",
            "__hash__",
            "__init__",
            "__init_subclass__",
            "__le__",
            "__lt__",
            "__module__",
            "__ne__",
            "__new__",
            "__reduce__",
            "__reduce_ex__",
            "__repr__",
            "__setattr__",
            "__sizeof__",
            "__str__",
            "__subclasshook__",
            "__weakref__",
            "_spawn",
            "serealize",
            "id",
            "spawn",
            "type",
        ]

        sensor_params = [attr for attr in dir(self) if attr not in ignored_params]

        for param in sensor_params:
            sensor_bp.set_attribute(param, str(getattr(self, param)))

        CarlaDataProvider.get_world().spawn_actor(sensor_bp, self.spawn, vehicle)
        CarlaDataProvider.get_world().wait_for_tick()

    def serealize(self):
        return self.type, self.id


class CameraRGB(DefaultSensor):
    """
    A class to hold additional information about a camera sensor
    """

    def __init__(self) -> None:
        super().__init__()
        self.image_size_x: int = 0
        self.image_size_y: int = 0
        self.fov: float = 0.0


class LidarRayCast(DefaultSensor):
    """
    A class to hold additional information about a Lidar sensor
    """

    def __init__(self) -> None:
        super().__init__()
        self.range: int = 0
        self.channels: int = 0
        self.points_per_second: int = 0
        self.upper_fov: float = 0.0
        self.lower_fov: float = 0.0
        self.rotation_frequency: int = 0


class SensorGNSS(DefaultSensor):
    """
    A class to hold additional information about GNSS
    """

    def __init__(self) -> None:
        super().__init__()
        self.noise_alt_stddev = 0.0
        self.noise_lat_stddev = 0.0
        self.noise_lon_stddev = 0.0
        self.noise_alt_bias = 0.0
        self.noise_lat_bias = 0.0
        self.noise_lon_bias = 0.0


class SensorIMU(DefaultSensor):
    """
    A class to hold additional information about IMU
    """

    def __init__(self) -> None:
        super().__init__()
        self.noise_accel_stddev_x = 0.0
        self.noise_accel_stddev_y = 0.0
        self.noise_accel_stddev_z = 0.0
        self.noise_gyro_stddev_x = 0.0
        self.noise_gyro_stddev_y = 0.0
        self.noise_gyro_stddev_z = 0.0


class EnvironmentParser(object):
    """
    Purely Static class for parsing Scenarion configuration files generated by the JSON parsers
    """

    logger = logging.getLogger("scenario-runner")

    @staticmethod
    def parse_scenario_env(path: str) -> EnvironmentConfig:
        config = EnvironmentConfig()

        tree = ET.parse(path)

        for scenario in tree.iter("scenario"):
            config.town = scenario.attrib.get("town", "")
            config.route_id

            for elem in scenario.iter():
                if elem.tag == "ego_vehicle":
                    EnvironmentParser.parse_ego_config(config, elem)

        print(config.sensor_config[0].fov)
        return config

    @staticmethod
    def parse_ego_config(config: EnvironmentConfig, elem: Element) -> None:
        config.ego_model = elem.attrib.get("model", "")
        config.ego_name = elem.attrib.get("name", "")

        # build the rotation of the ego - we are only concerned with yaw (Z)
        ego_rotation = carla.Rotation(0.0, float(elem.attrib.get("yaw", 0.0)), 0.0)

        ego_location = carla.Location(
            float(elem.attrib.get("x", 0.0)),
            float(elem.attrib.get("y", 0.0)),
            float(elem.attrib.get("z", 0.0)),
        )

        config.ego_spawn = carla.Transform(ego_location, ego_rotation)

        sensors = []

        # parse the sensor configurations
        for sensor in elem.iter("sensor"):
            sensor_type = sensor.attrib.get("type", "")
            if sensor_type == "":
                EnvironmentParser.logger.error(
                    "Please include a sensor type, skipping sensor..."
                )
                continue

            spawn = sensor.find("spawn_point")

            sensor_obj = DefaultSensor()

            if sensor_type == "sensor.camera.rgb":
                sensor_obj = CameraRGB()
                sensor_obj.image_size_x = sensor.attrib.get("image_size_x", 0)
                sensor_obj.image_size_y = sensor.attrib.get("image_size_y", 0)
                sensor_obj.fov = sensor.attrib.get("fov", 0.0)

            elif sensor_type == "sensor.lidar.ray_cast":
                sensor_obj = LidarRayCast()
                sensor_obj.channels = sensor.attrib.get("channels", 0)
                sensor_obj.points_per_second = sensor.attrib.get("points_per_second", 0)
                sensor_obj.upper_fov = sensor.attrib.get("upper_fov", 0.0)
                sensor_obj.lower_fov = sensor.attrib.get("lower_fov", 0.0)
                sensor_obj.rotation_frequency = sensor.attrib.get(
                    "rotation_frequency", 0
                )

            sensor_obj.type = sensor_type
            sensor_obj.id = sensor.attrib.get("id", "")

            if spawn is not None:
                sensor_obj.spawn = carla.Transform(
                    carla.Location(
                        float(spawn.attrib.get("x", 0.0)),
                        float(spawn.attrib.get("y", 0.0)),
                        float(spawn.attrib.get("z", 0.0)),
                    ),
                    carla.Rotation(
                        float(spawn.attrib.get("pitch", 0.0)),
                        float(spawn.attrib.get("yaw", 0.0)),
                        float(spawn.attrib.get("roll", 0.0)),
                    ),
                )
            else:
                EnvironmentParser.logger.error(
                    "Please include a spawn location for the sensor..."
                )
                continue

            sensors.append(sensor_obj)

        config.sensor_config = sensors
